export interface Country {
  name: string;
  cities: string[];
}

export const countries: Country[] = [
  {
    name: "Guinée",
    cities: [
      "Conakry",
      "Kindia",
      "Kankan",
      "Labé",
      "Nzérékoré",
      "Boké",
      "Mamou",
      "Kissidougou",
      "Siguiri",
      "Faranah",
    ],
  },
  {
    name: "France",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],
  },
  {
    name: "Sénégal",
    cities: [
      "Dakar",
      "Touba",
      "Thiès",
      "Kaolack",
      "Saint-Louis",
      "Ziguinchor",
      "Mbour",
      "Rufisque",
      "Kolda",
      "Diourbel",
    ],
  },
  {
    name: "Côte d'Ivoire",
    cities: [
      "Abidjan",
      "Yamoussoukro",
      "Bouaké",
      "Daloa",
      "San-Pédro",
      "Korhogo",
      "Man",
      "Divo",
      "Gagnoa",
      "Abengourou",
    ],
  },
  {
    name: "Mali",
    cities: [
      "Bamako",
      "Sikasso",
      "Mopti",
      "Koutiala",
      "Kayes",
      "Ségou",
      "Gao",
      "Kati",
      "Tombouctou",
      "Markala",
    ],
  },
  {
    name: "Bénin",
    cities: [
      "Cotonou",
      "Porto-Novo",
      "Parakou",
      "Djougou",
      "Bohicon",
      "Kandi",
      "Abomey",
      "Lokossa",
      "Ouidah",
      "Natitingou",
    ],
  },
  {
    name: "Burkina Faso",
    cities: [
      "Ouagadougou",
      "Bobo-Dioulasso",
      "Koudougou",
      "Ouahigouya",
      "Banfora",
      "Dédougou",
      "Kaya",
      "Fada N'gourma",
      "Tenkodogo",
      "Houndé",
    ],
  },
  {
    name: "Togo",
    cities: [
      "Lomé",
      "Sokodé",
      "Kara",
      "Kpalimé",
      "Atakpamé",
      "Bassar",
      "Tsévié",
      "Aného",
      "Sansanné-Mango",
      "Dapaong",
    ],
  },
  {
    name: "Niger",
    cities: [
      "Niamey",
      "Zinder",
      "Maradi",
      "Agadez",
      "Tahoua",
      "Dosso",
      "Diffa",
      "Tillabéri",
      "Arlit",
      "Birni N'Konni",
    ],
  },
  {
    name: "Belgique",
    cities: [
      "Bruxelles",
      "Anvers",
      "Gand",
      "Charleroi",
      "Liège",
      "Bruges",
      "Namur",
      "Louvain",
      "Mons",
      "Malines",
    ],
  },
  {
    name: "Canada",
    cities: [
      "Toronto",
      "Montréal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Québec",
      "Hamilton",
      "Kitchener",
    ],
  },
  {
    name: "États-Unis",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphie",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San José",
    ],
  },
  {
    name: "Cameroun",
    cities: [
      "Yaoundé",
      "Douala",
      "Garoua",
      "Bafoussam",
      "Bamenda",
      "Maroua",
      "Nkongsamba",
      "Bertoua",
      "Ngaoundéré",
      "Kribi",
    ],
  },
  {
    name: "République centrafricaine",
    cities: [
      "Bangui",
      "Bimbo",
      "Berbérati",
      "Carnot",
      "Bambari",
      "Bouar",
      "Bossangoa",
      "Bria",
      "Bangassou",
      "Nola",
    ],
  },
  {
    name: "Tchad",
    cities: [
      "N'Djamena",
      "Moundou",
      "Sarh",
      "Abéché",
      "Kélo",
      "Koumra",
      "Pala",
      "Am Timan",
      "Bongor",
      "Doba",
    ],
  },
  {
    name: "Congo-Brazzaville",
    cities: [
      "Brazzaville",
      "Pointe-Noire",
      "Dolisie",
      "Nkayi",
      "Ouesso",
      "Owando",
      "Impfondo",
      "Madingou",
      "Loandjili",
      "Djambala",
    ],
  },
  {
    name: "République démocratique du Congo",
    cities: [
      "Kinshasa",
      "Lubumbashi",
      "Mbuji-Mayi",
      "Kisangani",
      "Kananga",
      "Likasi",
      "Kolwezi",
      "Tshikapa",
      "Beni",
      "Bukavu",
    ],
  },
  {
    name: "Guinée équatoriale",
    cities: [
      "Malabo",
      "Bata",
      "Ebebiyin",
      "Aconibe",
      "Añisoc",
      "Luba",
      "Evinayong",
      "Mongomo",
      "Nsok",
      "Rebola",
    ],
  },
  {
    name: "Gabon",
    cities: [
      "Libreville",
      "Port-Gentil",
      "Franceville",
      "Oyem",
      "Moanda",
      "Mouila",
      "Lambaréné",
      "Tchibanga",
      "Koulamoutou",
      "Makokou",
    ],
  },
  {
    name: "Sao Tomé-et-Principe",
    cities: [
      "São Tomé",
      "Santo António",
      "Trindade",
      "Neves",
      "Santana",
      "Guadalupe",
      "Ribeira Afonso",
      "Porto Alegre",
      "Santa Cruz",
      "Pantufo",
    ],
  },
  {
    name: "Angola",
    cities: [
      "Luanda",
      "Huambo",
      "Lubango",
      "Benguela",
      "Kuito",
      "Lobito",
      "Malanje",
      "Namibe",
      "Soyo",
      "Cabinda",
    ],
  },
];
